core/urls.py
from django.urls import path
from core import views

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('dashboard/', views.dashboard, name='dashboard'),
]

inventory/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "inventory"
urlpatterns = [
    path('items/', ItemListView.as_view(), name='item_list'),
    path('items/create/', ItemCreateView.as_view(), name='create_item'),
    path('items/<str:pk>/', ItemDetailView.as_view(), name='item_detail'),
    path('items/<str:pk>/edit/', ItemUpdateView.as_view(), name='edit_item'),
    path('items/<str:pk>/delete/', ItemDeleteView.as_view(), name='item_delete'),
    path("item_groups/", ItemGroupListView.as_view(), name="item_group_list"),
    path("item_groups/create/", CreateItemGroupView.as_view(), name="create_item_group"),
    path("item_groups/<int:pk>/", ItemGroupDetailView.as_view(), name="item_group_detail"),
    path("item_groups/<int:pk>/edit/", EditItemGroupView.as_view(), name="edit_item_group"),
    path('item_groups/<int:pk>/delete/', ItemGroupDeleteView.as_view(), name='item_group_delete'),
    path('unit_of_measurements/', UnitOfMeasurementListView.as_view(), name='unit_of_measurement_list'),
    path('unit_of_measurements/create/', CreateUnitOfMeasurementView.as_view(), name='create_unit_of_measurement'),
    path('unit_of_measurements/<int:pk>/', UnitOfMeasurementDetailView.as_view(), name='unit_of_measurement_detail'),
    path('unit_of_measurements/<int:pk>/edit/', EditUnitOfMeasurementView.as_view(), name='edit_unit_of_measurement'),
    path('unit_of_measurements/<int:pk>/delete/', UnitOfMeasurementDeleteView.as_view(), name='unit_of_measurement_delete'),
    path('item-settings/', ItemSettingsView.as_view(), name='item_settings'),
    path('', inventory, name='inventory'),
]

mrplite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inventory/', include("inventory.urls")),
    path('', include("core.urls")),
    path('account/', include("users.urls")),
    path('account/', include('django.contrib.auth.urls')),
]

inventory/models.py
from django.db import models
from django.contrib.auth.models import User


class ItemGroup(models.Model):
    item_group_number = models.AutoField(primary_key=True)
    item_group_name = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)

    def __str__(self):
        return self.item_group_name


class UnitOfMeasurement(models.Model):
    unit_of_measurement_id = models.AutoField(primary_key=True)
    unit_of_measurement = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)

    def __str__(self):
        return self.unit_of_measurement


class Item(models.Model):
    item_sku = models.CharField(max_length=50, primary_key=True)
    item_name = models.CharField(max_length=100, blank=True, null=True)
    item_group = models.ForeignKey(ItemGroup, on_delete=models.SET_NULL, blank=True, null=True)
    unit_of_measurement = models.ForeignKey(UnitOfMeasurement, on_delete=models.SET_NULL, blank=True, null=True)
    reorder_point = models.PositiveIntegerField(blank=True, null=True)
    selling_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    manufactured = models.BooleanField(blank=True, null=True)
    min_qty_for_manufacturing = models.PositiveIntegerField(blank=True, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    quantity = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, null=True)

    def __str__(self):
        return self.item_name

inventory/forms.py
from django import forms
from .models import Item, ItemGroup, UnitOfMeasurement


class ItemForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(ItemForm, self).__init__(*args, **kwargs)
        self.fields['item_group'].queryset = ItemGroup.objects.filter(user=user)
        self.fields['unit_of_measurement'].queryset = UnitOfMeasurement.objects.filter(user=user)
    class Meta:
        model = Item
        fields = ['item_sku', 'item_name', 'item_group', 'unit_of_measurement',
                  'reorder_point', 'selling_price', 'manufactured', 'min_qty_for_manufacturing']


class EditItemForm(forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super(EditItemForm, self).__init__(*args, **kwargs)
        self.fields['item_group'].queryset = ItemGroup.objects.filter(user=user)
        self.fields['unit_of_measurement'].queryset = UnitOfMeasurement.objects.filter(user=user)

    # cant update the sku
    class Meta:
        model = Item
        fields = ['item_name', 'item_group', 'unit_of_measurement',
                  'reorder_point', 'selling_price', 'manufactured', 'min_qty_for_manufacturing']


class InventoryQuantityForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['quantity']


class ItemGroupForm(forms.ModelForm):
    class Meta:
        model = ItemGroup
        fields = ['item_group_name']


class EditItemGroupForm(forms.ModelForm):
    class Meta:
        model = ItemGroup
        fields = ['item_group_name']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['item_group_name'].required = True  # Make item_group_name field required


class UnitOfMeasurementForm(forms.ModelForm):
    class Meta:
        model = UnitOfMeasurement
        fields = ['unit_of_measurement']


class EditUnitOfMeasurementForm(forms.ModelForm):
    class Meta:
        model = UnitOfMeasurement
        fields = ['unit_of_measurement']

inventory/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from .models import Item, ItemGroup, UnitOfMeasurement
from .forms import ItemForm, EditItemForm, \
    EditItemGroupForm, ItemGroupForm, \
    UnitOfMeasurementForm, EditUnitOfMeasurementForm, \
    InventoryQuantityForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required


class ItemListView(LoginRequiredMixin, ListView):
    model = Item
    template_name = 'inventory/item_list.html'
    context_object_name = 'items'
    ordering = ['item_sku']

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class ItemDetailView(LoginRequiredMixin, DetailView):
    model = Item
    template_name = 'inventory/item_detail.html'
    context_object_name = 'item'


class ItemCreateView(LoginRequiredMixin, CreateView):
    model = Item
    template_name = 'inventory/create_item.html'
    form_class = ItemForm

    def form_valid(self, form):
        form.instance.user = self.request.user  # set the user field of the object to be the user currently logged in
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Pass the currently logged-in user to the form
        return kwargs

    def get_success_url(self):
        return reverse_lazy('inventory:item_detail', kwargs={'pk': self.object.item_sku})


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    model = Item
    template_name = 'inventory/edit_item.html'
    form_class = EditItemForm
    context_object_name = 'item'

    def get_success_url(self):
        return reverse_lazy('inventory:item_detail', kwargs={'pk': self.object.item_sku})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


# need to create this template still
class ItemDeleteView(LoginRequiredMixin, DeleteView):
    model = Item
    template_name = 'inventory/item_confirm_delete.html'
    success_url = reverse_lazy('inventory:item_list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Item deleted successfully.')
        return super().delete(request, *args, **kwargs)


class ItemGroupListView(LoginRequiredMixin, ListView):
    model = ItemGroup
    template_name = 'inventory/item_group_list.html'
    context_object_name = 'item_groups'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class ItemGroupDetailView(LoginRequiredMixin, DetailView):
    model = ItemGroup
    template_name = 'inventory/item_group_detail.html'
    context_object_name = 'item_group'


class CreateItemGroupView(LoginRequiredMixin, CreateView):
    model = ItemGroup
    form_class = ItemGroupForm
    template_name = 'inventory/create_item_group.html'

    def form_valid(self, form):
        form.instance.user = self.request.user  # set the user field of the object to be the user currently logged in
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('inventory:item_group_detail', kwargs={'pk': self.object.pk})


class EditItemGroupView(LoginRequiredMixin, UpdateView):
    model = ItemGroup
    form_class = EditItemGroupForm
    template_name = 'inventory/edit_item_group.html'
    context_object_name = 'item_group'

    def form_valid(self, form):
        form.instance.user = self.request.user  # set the user field of the object to be the user currently logged in
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('inventory:item_group_detail', kwargs={'pk': self.object.pk})


class ItemGroupDeleteView(LoginRequiredMixin, DeleteView):
    model = ItemGroup
    template_name = 'inventory/item_group_confirm_delete.html'
    success_url = reverse_lazy('inventory:item_group_list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Item group deleted successfully.')
        return super().delete(request, *args, **kwargs)


class UnitOfMeasurementListView(LoginRequiredMixin, ListView):
    model = UnitOfMeasurement
    template_name = 'inventory/unit_of_measurement_list.html'
    context_object_name = 'unit_of_measurements'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


class UnitOfMeasurementDetailView(LoginRequiredMixin, DetailView):
    model = UnitOfMeasurement
    template_name = 'inventory/unit_of_measurement_detail.html'
    context_object_name = 'unit_of_measurement'


class CreateUnitOfMeasurementView(LoginRequiredMixin, CreateView):
    model = UnitOfMeasurement
    form_class = UnitOfMeasurementForm
    template_name = 'inventory/create_unit_of_measurement.html'

    def form_valid(self, form):
        form.instance.user = self.request.user  # set the user field of the object to be the user currently logged in
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('inventory:unit_of_measurement_detail', kwargs={'pk': self.object.pk})


class EditUnitOfMeasurementView(LoginRequiredMixin, UpdateView):
    model = UnitOfMeasurement
    form_class = EditUnitOfMeasurementForm
    template_name = 'inventory/edit_unit_of_measurement.html'
    context_object_name = 'unit_of_measurement'

    def get_success_url(self):
        return reverse_lazy('inventory:unit_of_measurement_detail', kwargs={'pk': self.object.pk})


class UnitOfMeasurementDeleteView(LoginRequiredMixin, DeleteView):
    model = UnitOfMeasurement
    template_name = 'inventory/unit_of_measurement_confirm_delete.html'
    success_url = reverse_lazy('inventory:unit_of_measurement_list')

    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Unit of measurement deleted successfully.')
        return super().delete(request, *args, **kwargs)


class ItemSettingsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        context = {
            'item_group_list_url': reverse_lazy('inventory:item_group_list'),
            'unit_of_measurement_list_url': reverse_lazy('inventory:unit_of_measurement_list'),
        }
        return render(request, 'inventory/item_settings.html', context)


@login_required
def inventory(request):
    items = Item.objects.filter(user=request.user).order_by('item_sku')
    if request.method == 'POST':
        form = InventoryQuantityForm(request.POST)
        print(request.POST)
        if form.is_valid():
            item_sku = request.POST.get('item_sku')
            print(item_sku)
            new_quantity = form.cleaned_data['quantity']
            item = Item.objects.get(item_sku=item_sku)
            item.quantity = new_quantity
            item.save()
            return redirect('inventory:inventory')  # Redirect to the inventory page after updating quantity
    else:
        form = InventoryQuantityForm()
    return render(request, 'inventory/inventory.html', {'items': items, 'inventory_form': form})

inventory/templates/inventory/create_item.html
{% extends 'adminlte/base.html' %}

{% block title %}Create New Item{% endblock %}

{% block content %}
<div class="container mt-10">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">Create New Item</div>

                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="col-sm-6">
                        <div class="form-group">
                            <label for="{{ form.item_sku.id_for_label }}">Item SKU*</label>
                            <input type="text" class="form-control" placeholder="Item SKU" name="{{ form.item_sku.html_name }}" id="{{ form.item_sku.id_for_label }}">
                        </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="{{ form.item_name.id_for_label }}">Item Name*</label>
                                <input type="text" class="form-control" placeholder="Item Name" name="{{ form.item_name.html_name }}" id="{{ form.item_name.id_for_label }}">
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="{{ form.item_group.id_for_label }}">Item Group</label>
                                <select class="form-control" name="{{ form.item_group.html_name }}">
    <!--                                <option value="create_new">Create New Item Group</option>-->
                                    {% for value, label in form.item_group.field.choices %}
                                        <option value="{{ value }}">{{ label }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="{{ form.unit_of_measurement.id_for_label }}">Unit of Measurement</label>
                                <select class="form-control" name="{{ form.unit_of_measurement.html_name }}">
    <!--                                <option value="create_new">Create New Item Group</option>-->
                                    {% for value, label in form.unit_of_measurement.field.choices %}
                                        <option value="{{ value }}">{{ label }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label for="{{ form.reorder_point.id_for_label }}">Reorder Point</label>
                                <input type="int" class="form-control" placeholder="Reorder Point" name="{{ form.reorder_point.html_name }}" id="{{ form.reorder_point.id_for_label }}">
                            </div>
                        </div>

                        <div class="col-sm-3">
                            <div class="form-group">
                                <label for="{{ form.selling_price.id_for_label }}">Selling Price</label>
                                <div class="input-group">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text">
                                            <i class="fas fa-dollar-sign"></i>
                                        </span>
                                    </div>
                                    <input type="text" class="form-control" placeholder="Price per Unit" name="{{ form.selling_price.html_name }}" id="{{ form.selling_price.id_for_label }}">
                                </div>
                            </div>
                        </div>


                        <div class="row">
                            <div class="col-sm-3 d-flex align-items-center" style="height: 100px">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="manufacturedCheckbox">
                                    <label class="form-check-label" for="{{ form.manufactured.id_for_label }}" id="{{ form.manufactured.id_for_label }} ">This item is manufactured</label>
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="form-group" id="minQtyManufacturingFieldWrapper">
                                    <label for="{{ form.min_quantity_for_manufacturing.id_for_label }}">Minimum Quantity for Manufacturing</label>
                                    <input type="text" class="form-control" placeholder="Min. Qty for Manufacturing" name="{{ form.min_quantity_for_manufacturing.html_name }}" id="{{ form.min_quantity_for_manufacturing.id_for_label }}">
                                </div>
                            </div>
                        </div>
                        <a href="{% url 'inventory:item_list' %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        var manufacturedCheckbox = document.getElementById('manufacturedCheckbox');
        var minQtyManufacturingFieldWrapper = document.getElementById('minQtyManufacturingFieldWrapper');

        // Initially hide the "Minimum Quantity for Manufacturing" field
        minQtyManufacturingFieldWrapper.style.display = 'none';

        // Add event listener to checkbox
        manufacturedCheckbox.addEventListener('change', function () {
            // If checkbox is checked, show the field; otherwise, hide it
            if (manufacturedCheckbox.checked) {
                minQtyManufacturingFieldWrapper.style.display = 'block';
            } else {
                minQtyManufacturingFieldWrapper.style.display = 'none';
            }
        });
    });
</script>
{% endblock %}

inventory/templates/inventory/create_unit_of_measurement.html
{% extends 'adminlte/base.html' %}

{% block title %}Create Unit of Measurement{% endblock %}

{% block content %}
    <div class="container mt-10">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">Create Unit of Measurement</div>

                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="{{ form.unit_of_measurement.id_for_label }}">Unit of Measurement*</label>
                                <input type="text" class="form-control" placeholder="Unit of Measurement" name="{{ form.unit_of_measurement.html_name }}" id="{{ form.unit_of_measurement.id_for_label }}">
                            </div>
                        </div>

                        <a href="{% url 'inventory:item_settings' %}" class="btn btn-secondary">Cancel</a>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inventory/templates/inventory/item_detail.html
{% extends 'adminlte/base.html' %}

{% block title %}Inventory{% endblock %}

{% block content %}
<div class="container mt-10">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">{{ item.item_sku }} {{ item.item_name }} Details</div>

                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="item_sku">Item SKU</label>
                                <input type="text" class="form-control" value="{{ item.item_sku }}" readonly>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="item_name">Item Name</label>
                                <input type="text" class="form-control" value="{{ item.item_name }}" readonly>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="item_group">Item Group</label>
                                <input type="text" class="form-control" value="{{ item.item_group }}" readonly>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="unit_of_measurement">Unit of Measurement</label>
                                <input type="text" class="form-control" value="{{ item.unit_of_measurement }}" readonly>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="reorder_point">Reorder Point</label>
                                <input type="text" class="form-control" value="{{ item.reorder_point }}" readonly>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="selling_price">Selling Price</label>
                                <input type="text" class="form-control" value="{{ item.selling_price }}" readonly>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="manufactured">Manufactured</label>
                                <input type="text" class="form-control" value="{{ item.manufactured }}" readonly>
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="form-group">
                                <label for="min_qty_for_manufacturing">Min. Quantity for Manufacturing</label>
                                <input type="text" class="form-control" value="{{ item.min_qty_for_manufacturing }}" readonly>
                            </div>
                        </div>

                        <a href="{% url 'inventory:item_list' %}" class="btn btn-secondary">Back</a>
                        <a href="{% url 'inventory:edit_item' pk=item.item_sku %}" class="btn btn-primary">Edit</a>
                        <button type="submit" class="btn btn-danger" id="deleteButton" style="position: absolute; bottom: 10px; right: 10px;">
                            <i class="fas fa-trash-alt"></i>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inventory/templates/inventory/item_group_detail.html
{% extends 'adminlte/base.html' %}

{% block title %}Item Group Detail{% endblock %}

{% block content %}
<div class="container mt-10">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">Item Group {{ item_group.item_group_name }} Details</div>

                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="item_group_number">Number</label>
                            <input type="text" class="form-control" name="item_group_number" value="{{ item_group.item_group_number }}" readonly>
                        </div>

                        <div class="form-group">
                            <label for="item_group_name">Name</label>
                            <input type="text" class="form-control" name="item_group_name" value="{{ item_group.item_group_name }}" readonly>
                        </div>

                        <a href="{% url 'inventory:edit_item_group' pk=item_group.pk %}" class="btn btn-primary">Edit</a>
                        <a href="{% url 'inventory:item_group_list' %}" class="btn btn-secondary">Back</a>
                        <button type="submit" class="btn btn-danger" id="deleteButton" style="position: absolute; bottom: 10px; right: 10px;">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inventory/templates/inventory/item_group_list.html
{% extends 'adminlte/base.html' %}

{% block title %}Item Group List{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-auto">
                            <h1>Item Groups</h1>
                        </div>
                        <div class="col-auto">
                            <a href="{% url 'inventory:create_item_group' %}" class="btn btn-primary">+ New Item Group</a>
                        </div>
                    </div>
                </div>
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Item Group Name</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item_group in item_groups %}
                            <tr>
                                <td><a href="{% url 'inventory:item_group_detail' pk=item_group.pk %}">{{ item_group.item_group_name }}</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <a href="{% url 'inventory:item_settings' %}" class="btn btn-secondary">Back</a>
        </div>
    </div>
{% endblock %}

inventory/templates/inventory/unit_of_measurement_detail.html
{% extends 'adminlte/base.html' %}

{% block title %}Unit of Measurement Detail{% endblock %}

{% block content %}
<div class="container mt-10">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">Unit of Measurement {{ unit_of_measurement.unit_of_measurement }} Details</div>

                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="unit_of_measurement_id">ID</label>
                            <input type="text" class="form-control" name="unit_of_measurement_id" value="{{ unit_of_measurement.pk }}" readonly>
                        </div>

                        <div class="form-group">
                            <label for="unit_of_measurement_name">Name</label>
                            <input type="text" class="form-control" name="unit_of_measurement_name" value="{{ unit_of_measurement.unit_of_measurement }}" readonly>
                        </div>

                        <a href="{% url 'inventory:unit_of_measurement_list' %}" class="btn btn-secondary">Back</a>
                        <a href="{% url 'inventory:edit_unit_of_measurement' pk=unit_of_measurement.pk %}" class="btn btn-primary">Edit</a>
                        <button type="submit" class="btn btn-danger" id="deleteButton" style="position: absolute; bottom: 10px; right: 10px;">
                            <i class="fas fa-trash-alt"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

inventory/templates/inventory/unit_of_measurement_list.html
{% extends 'adminlte/base.html' %}

{% block title %}Unit of Measurement List{% endblock %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-auto">
                        <h1>Units of Measurement</h1>
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'inventory:create_unit_of_measurement' %}" class="btn btn-primary">+ New UoM</a>
                    </div>
                </div>
            </div>
            <div class="card-body table-responsive p-0">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Unit of Measurement</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for unit_of_measurement in unit_of_measurements %}
                        <tr>
                            <td><a href="{% url 'inventory:unit_of_measurement_detail' pk=unit_of_measurement.pk %}">{{ unit_of_measurement.unit_of_measurement }}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

        </div>
        <a href="{% url 'inventory:item_settings' %}" class="btn btn-secondary">Back</a>
    </div>
</div>
{% endblock %}